services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=parcellab
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "16379:6379"

volumes:
  postgres_data:
  redis_data: 