"""Initial migration

Revision ID: dcb68c87f04d
Revises:
Create Date: 2025-04-22 21:43:08.402231

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dcb68c87f04d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracking_number", sa.String(), nullable=False),
        sa.Column("carrier", sa.String(), nullable=True),
        sa.Column("sender_address", sa.String(), nullable=True),
        sa.Column("receiver_address", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "active",
                "pending",
                "transit",
                "in_transit",
                "inbound_scan",
                "delivery",
                "scanned",
                "failed",
                "canceled",
                "returned",
                "lost",
                name="shipmentstatus",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shipment_carrier"), "shipment", ["carrier"], unique=False)
    op.create_index(op.f("ix_shipment_id"), "shipment", ["id"], unique=False)
    op.create_index(op.f("ix_shipment_status"), "shipment", ["status"], unique=False)
    op.create_index(op.f("ix_shipment_tracking_number"), "shipment", ["tracking_number"], unique=True)
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipment_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("sku", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_article_id"), "article", ["id"], unique=False)
    op.create_index(op.f("ix_article_sku"), "article", ["sku"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_article_sku"), table_name="article")
    op.drop_index(op.f("ix_article_id"), table_name="article")
    op.drop_table("article")
    op.drop_index(op.f("ix_shipment_tracking_number"), table_name="shipment")
    op.drop_index(op.f("ix_shipment_status"), table_name="shipment")
    op.drop_index(op.f("ix_shipment_id"), table_name="shipment")
    op.drop_index(op.f("ix_shipment_carrier"), table_name="shipment")
    op.drop_table("shipment")
    op.execute("drop type shipmentstatus;")
    # ### end Alembic commands ###
